version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - '9092:9092'
    environment:
      # 1. KRaft 모드 설정 (Zookeeper 제거)
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # 2. 리스너 설정
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      # 3. 외부 노출 IP 설정 (환경 변수 사용)
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${MY_PRIVATE_IP}:9092

      # 4. 메모리 제한
      - KAFKA_HEAP_OPTS=-Xmx400m -Xms400m

    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data: